/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proxy.panels;

import java.io.*;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author root
 */
public class FileEdit extends javax.swing.JPanel
{   Setting s;
     JTextArea TA;
    public FileEdit()
    {
        initComponents();
        s=new Setting();
        TA=TextArea;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BSQreload = new javax.swing.JButton();
        BSQsave = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        BSQreload.setText("RELOAD");
        BSQreload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSQreloadActionPerformed(evt);
            }
        });

        BSQsave.setText("SAVE");
        BSQsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSQsaveActionPerformed(evt);
            }
        });

        TextArea.setColumns(20);
        TextArea.setRows(5);
        jScrollPane1.setViewportView(TextArea);

        jLabel1.setText("squid.conf  file");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1039, Short.MAX_VALUE)
                .addComponent(BSQreload)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BSQsave))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BSQreload)
                    .addComponent(BSQsave)
                    .addComponent(jLabel1)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BSQreloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSQreloadActionPerformed
        this.setEnabled(false);
        TextArea.setText(s.loadFile());
        JOptionPane.showMessageDialog(null,"RELOADED SUCCESSFULLY"); 
    }//GEN-LAST:event_BSQreloadActionPerformed

    private void BSQsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSQsaveActionPerformed
       File file = null;
        FileWriter out=null;
        try {
            file = new File("/etc/squid/squid.conf");
            out = new FileWriter(file);     
            out.write(TextArea.getText());
            out.close();
            JOptionPane.showMessageDialog(null,"SAVED SUCCESSFULLY");
            
        }catch (Exception e) {
         JOptionPane.showMessageDialog(null,"EXCEPTION WHILE SAVING FILE "+e); 
        }
    }//GEN-LAST:event_BSQsaveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BSQreload;
    private javax.swing.JButton BSQsave;
    private javax.swing.JTextArea TextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
