/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proxy.panels;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;
import static proxy.panels.Setting.storeAllString;

/**
 *
 * @author root
 */
public class StatusShow extends javax.swing.JPanel {

    private FileEdit fe;

    /**
     * Creates new form StatusShow
     */
    public StatusShow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        BOpenSquid = new javax.swing.JButton();

        TextArea.setColumns(20);
        TextArea.setRows(5);
        jScrollPane1.setViewportView(TextArea);

        jLabel1.setText("CONFIGURATION FILE ");

        BOpenSquid.setText("squid.conf");
        BOpenSquid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOpenSquidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1029, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BOpenSquid, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(BOpenSquid)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BOpenSquidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOpenSquidActionPerformed
        this.setVisible(false);
        fe.setVisible(true);
        fe.TA.setText(loadFile());
    }//GEN-LAST:event_BOpenSquidActionPerformed

    public void setText(String lines) {
     TextArea.setText(lines);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BOpenSquid;
    private javax.swing.JTextArea TextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public void setFileEdit(FileEdit fe) {
     this.fe=fe;    
    }

    private String loadFile()
    {
        BufferedReader reader;
              storeAllString="";
		try 
                {
			reader = new BufferedReader(new FileReader(
					"/etc/squid/squid.conf"));
			String line = reader.readLine();
			while (line != null)
                        {       storeAllString=storeAllString+line+"\n";
                                //System.out.println(line);
				line = reader.readLine();       
			}
                      // TextArea.setText(storeAllString);
			reader.close();
                        return storeAllString;
		}
                catch(IOException e)
                {
		JOptionPane.showMessageDialog(null,"EXCEPTION "+e); 
		}
                return "EMPTY";
    }
}
